#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    value_min = scores[0]
    value_max = scores[0]
    minn,maxx = 0,0 
    for i in range(1,len(scores)):
        if value_min > scores[i]:
            value_min = scores[i]
            minn += 1
        elif value_max < scores[i]:
            value_max = scores[i]
            maxx += 1
    
    return maxx,minn
             
    
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
