#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    lst=[]
    arr = sorted(arr)
    minn = 0
    maxx = 0
    for i in range(len(arr)):
        if i < 4:
            minn = minn + arr[i]
        if i > 0:
            maxx = maxx + arr[i]
    print(minn,maxx)
        
    # Write your code here

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
