#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    l,m,n = 0,0,0
    for i in range(len(arr)):
        if arr[i] > 0:
            l += 1
        elif arr[i] < 0:
            m += 1
        else:
            n += 1
    print("%.6f"%(l/len(arr)))
    print("%.6f"%(m/len(arr)))
    print("%.6f"%(n/len(arr)))

    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
